### ISSUE TITLE
Name im Browser-Tag

### ISSUE THREAD

**Issue by gemeinga-manager** [community-garden/community-garden.github.io#2]
Noch haben wir kein Logo zum Einbinden, aber schonmal "Pergola" als Name wäre hilfreich, denn derzeit findet sich der Tag im Browser nur schwerlich.

**Comment by pminf** [comment]
Ich habe einen Titel ergänzt. Auf der Startseite lautet er: "Pergola | Community Garden App". Bei den Blog Posts ist er dynamisch entsprechend des Post Titels.

**Comment by gemeinga-manager** [comment]
Das wird bei mir leider nicht angezeigt. Ich habe als mögliche Fehlerquelle Cockie, Cache, Verlauf etc. des Browsers geleert - keine Besserung. Woran kann´s noch liegen?
