### ISSUE TITLE
Nav auf Website fixen

### ISSUE THREAD

**Issue by cariboula** [community-garden/community-garden.github.io#20]
aktuelle Position auf Website sollte ersichtlich sein

**Comment by pminf** [comment]
Ein vermeintlich einfacher Use-Case, der aber bei Reach Router alles andere als gut dokumentiert ist. Letztlich bin ich über https://github.com/reach/router/issues/297, https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-link/ und https://reach.tech/router/api/Match zu einer Lösung gekommen. :-!

@bastiion Bitte um Review :)
