### ISSUE TITLE
Milestone Übersetzen ,die englische Version drunter zu setzen und aus der ersten Zeile zu verlinken

### ISSUE THREAD

**Issue by bastiion** [community-garden/community-garden.github.io#22]
@bastiion Ich habe die Meilensteine ausformuliert. Übernimmst du bitte das Übersetzen? Ist es möglich, die englische Version drunter zu setzen und aus der ersten Zeile zu verlinken?

https://github.com/community-garden/community-garden.github.io/wiki/Meilensteine

_Originally posted by @gemeinga-manager in https://github.com/community-garden/community-garden.github.io/issues/6#issuecomment-747996102_

**Comment by gemeinga-manager** [comment]
https://github.com/community-garden/community-garden.github.io/issues/6
