### ISSUE TITLE
Website fixen

### ISSUE THREAD

**Issue by cariboula** [community-garden/community-garden.github.io#25]
- [x] bei den Blogartikeln gibt es jetzt auch "Pergola" - mit vier Anstrichen zur Namensdefinition. Ich vermute, der Artikel war alles andere als fertig, ist jetzt aber live.

- [x] bei den Milestones ist das Bild mit dem Gantt Diagramm zu groß geraten (#6)
- [x] unter Team wird wieder der (unvollständige, mit unterschiedlichen Bildgrößen versehene) Wikiartikel gezogen anstatt der Cards
- [ ] Projekt: deutschen Version aus 1. Zeile verlinken
- [x] Milestone: ebenso (#6)
- [x] Milestone: Überschrift deute Version beinhaltet Code - Sprunglink funktioniert deswegen nicht
- [ ] bei den Blogartikel, die Sprachangabe mit auflisten
- [ ] Vorschau Blogartikel wieder anpassen: https://github.com/community-garden/community-garden.github.io/issues/3 
- [ ] im Footer das Impressum/ Kontakt einfügen (oder wo auch immer)
- [ ] Team: Reihenfolge anpassen (Sebsatian, Claudia, Stephanie, Philipp, Johannes), Bild Philipp zu groß, Cards auf dem Screen zentrieren
- [x] Tippfehler auf Projektseite anpassen - Übersetzung (z. B. Datentrasnparanz)
- [ ] Links (z.B. bei Meilensteine) in neuem Browserfenster öffnen

**Comment by cariboula** [comment]
Team-Inhalt von und für Joe (wäre für die Card Ansicht zu übernehmen):

DE: Joe, Entwicker und Enthusiast von Free and Open Source Software. Hackt meist im Keller des lokalen CCC, bei schönem Wetter auch mal im Internationalen Garten.

EN: Joe, developer, free and open-source software enthusiast. Most of the time hacking at the local hackerspace, in case of nice weather sometimes at the International Garden.

**Comment by pminf** [comment]
> bei den Blogartikel, die Sprachangabe mit auflisten

@bastiion Ich hatte die getrennte Ausgabe entsprechend der Sprache bereits vorbereitet: https://github.com/community-garden/community-garden.github.io/pull/15 Wie dort bereits kommentiert, scheitert es am fehlenden Sprachparameter. `lang` ist nie gesetzt. Ich weiß aber nicht warum bzw. wo das ermittelt wird.

**Comment by cariboula** [comment]
@bastiion Ich habe alle oben gelisteten Änderungen in den Wiki-Einträgen "Home" (auf der Seite Project) und "Milestones" getätigt. <a> tags für die Sprunglinks habe ich aus der Überschrift rauszogen, bitte nach deployment nochmal testen ob ds so funktioniert.

Ansonsten müssten die neu deployed werden :)

**Comment by gemeinga-manager** [comment]
@bastiion Die Links zur dt. Version funktionieren bei "Projekt" und "Meilensteine" leider nicht.

**Comment by cariboula** [comment]
alle offenen Punkte über Language Toggle gelöst bzw. als separate Issues angelegt -> Issue wird geschlossen
