### ISSUE TITLE
Blogartikel mit Vorschau

### ISSUE THREAD

**Issue by gemeinga-manager** [community-garden/community-garden.github.io#3]
Derzeit gibt es nur einen kryptischen Link zum ersten Blogartikel. Das ist wenig einladend! Könnte da nicht auch die Vorschau (Titel, evtl. Statistik) auf den Artikel zu sehen sein?

**Comment by pminf** [comment]
Ich habe hier leider nicht viele Möglichkeiten. Ein Blog-Post besteht an sich nur aus Titel (=Dateiname), Body und ID. Ich habe die erste Headline 1. Grades aus dem Body nun als Linktext verwendet. Gerne hätte ich auch einen Teasertext oder ähnliches aber ich wüsste nicht, wie man den definieren kann. @bastiion, du vielleicht?

**Comment by gemeinga-manager** [comment]
So sieht es wesentlich besser aus! 
Doch mir fehlt ein wenig die Struktur für die Zweisprachigkeit: können wir Sprachkürzel (DE, ENG) davorsetzen? Mit Farbe arbeiten? Darauf achten, dass sich deutsch und engl. immer abwechseln? 2 Spalten anlegen?
... irgendetwas, das sich schnell realisieren lässt. Bitte @pminf

**Comment by gemeinga-manager** [comment]
https://github.com/community-garden/community-garden.github.io/issues/25
