### ISSUE TITLE
PT-Präsentationstext schreiben

### ISSUE THREAD

**Issue by gemeinga-manager** [community-garden/community-garden.github.io#32]
Das Prototype-Team bittet uns um einen Text inkl. Grafiken und Link zur Demoversion um unseren Prototypen zukünftig präsentieren zu können.  Folgende Tipps dazu von Marie:

Habt ihr schon überlegt, worüber ihr genau schreiben möchtet? Natürlich
ist das Hauptthema euer Projekt, aber wir haben festgestellt, dass Texte
meistens interessanter sind, wenn man 1-2 Aspekte als Hauptfokus festlegt.

Wichtig sind nicht nur die Fragen
"Was habe ich gebaut?"
"Wie habe ich es gebaut?",
sondern auch
"Warum habe ich es gebaut?"
"Welches Problem möchte ich lösen?"
"Was habe ich dabei gelernt, was für Menschen/Projekte/etc interessant
sein könnte?"
"Was sind die nächste Schritte für das Projekt/für die Gesellschaft?"
"Was war besonders herausfordernd?"
usw.

Was nicht funktioniert, sind Texte, die nur sagen "wir haben das gebaut,
und dafür haben wir zuerst X gemacht, dann Y und dann Z" - oder Texte,
die zu/nur technisch sind.

**Comment by gemeinga-manager** [comment]
erster Ansatz:

https://github.com/community-garden/community-garden.github.io/wiki/Projekt-Pr%C3%A4sentation

**Comment by cariboula** [comment]
Ich fänd es relativ super, wenn wir hier (zusätzlich) die **Blogbeiträge** verwenden. Die geben sehr viele ausführliche Antworten auf die aufgeführten Fragen.
@gemeinga-manager Dein Ansatz lässt sich glaub gut ergänzend in eine Grafik / einen Zeitstrahl verwandeln.

**Comment by gemeinga-manager** [comment]
![5Leute](https://user-images.githubusercontent.com/72280627/107221814-6d441280-6a14-11eb-8f09-8926d688749e.jpg)

**Comment by gemeinga-manager** [comment]
![Worte_klein](https://user-images.githubusercontent.com/72280627/107363312-3fc19c80-6ada-11eb-9037-3bb289e6ca9a.jpg)
![liste_klein](https://user-images.githubusercontent.com/72280627/107363307-3df7d900-6ada-11eb-992d-4d65551867f4.jpg)
![Software_klein](https://user-images.githubusercontent.com/72280627/107516487-c5ae1800-6bac-11eb-8da4-a5bbf08b9c76.jpg)
![5Leute_klein](https://user-images.githubusercontent.com/72280627/107363305-3d5f4280-6ada-11eb-8b73-13553a37359a.jpg)
![online_klein](https://user-images.githubusercontent.com/72280627/107363308-3e906f80-6ada-11eb-92b4-32de0135e803.jpg)
![pergola_icon_klein](https://user-images.githubusercontent.com/72280627/107363309-3f290600-6ada-11eb-9bb7-37327dfd1865.jpg)


![pergola_icon_mittel](https://user-images.githubusercontent.com/72280627/107369762-74395680-6ae2-11eb-953f-3a1f7334ffe1.jpg)

**Comment by gemeinga-manager** [comment]
![TopFeatures_Endstand](https://user-images.githubusercontent.com/72280627/107363457-7697b280-6ada-11eb-85d5-d359a223d1db.jpg)

**Comment by gemeinga-manager** [comment]
[Vorhabensbeschreibung.pdf](https://github.com/community-garden/community-garden.github.io/files/5951332/Vorhabensbeschreibung.pdf)
