### ISSUE TITLE
Anregungen von Marie (Mail vom 24.11.)

### ISSUE THREAD

**Issue by gemeinga-manager** [community-garden/community-garden.github.io#4]
@pminf Bitte bastel dir hieraus selbst Issues, wenn du diese benötigst. Einiges doppelt sich ja mit den schon vorhandenen.

Die Webseite sieht auf jeden Fall schön aus - bei Team und Milestones
bekomme ich ein 404, gehe aber davon aus, dass ihr da einfach noch nicht
so weit seid ;)
- Details: Prototype Fund schreibt man mit großen P und F, dafür App mit
kleinem a.
- Denkt bitte an das BMBF-Logo - Infos dazu findet ihr im
Zuwendungsbescheid.
- Das Bild oben ist echt super schön, aber wenn ihr es ein bisschen
kleiner (also weniger hoch) macht, kann man mehr über euch lesen, ohne
zu scrollen, und dann wird schneller klar, worum es beim Projekt geht.
- Ich würde die "Project"-Seite auch noch mit der Info ergänzen, wann es
eine erste Version geben wird bzw was gerade der Status ist, vielleicht
auch mit Link zu bereits existierenden Repos auf Github, wenn diese
öffentlich sind.
- Vielleicht der Blog übersichtlicher, wenn man dort direkt die Posts
sehen kann, statt nur Links?
- Die Bilder im Blogpost sind richtig, richtig cool! Vielleicht wäre es
hilfreich, ähnliche Grafiken auch auf die Startseite zu haben, die ein
Überblick geben :) (der Post selbst klingt irgendwie nicht fertig, aber
ich gehe davon aus, dass ihr noch daran arbeitet?)

**Comment by cariboula** [comment]
Alle  Anregungen in Issues verpackt.
